server:
  port: 8080
  servlet:
    context-path: /
# 配置数据库连接池
spring:
  datasource:
    name: druid
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/assistance?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  # 访问的本地资源路径 修改文件保存路径时修改此路径即可
  web:
    resources:
      static-locations: file:F:\\UPLOAD
  # 设置最大上传文件大小限制
  servlet:
    multipart:
      # 设置最大上传文件大小
      max-file-size: 10MB
      # 设置整个请求的大小
      max-request-size: 15MB


  # 加载Mybatis配置文件
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

